### ISSUE TITLE
 Problem 1 - The requested package skeeks/yii2-widget-simpleajaxloader could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by search2074** [skeeks-semenov/yii2-widget-simpleajaxuploader#1]
Yo!

Не устанавливается пакет, поправьте, плыз, строчку в readme

> "skeeks/yii2-widget-simpleajaxloader": "*"

на

> "skeeks/yii2-widget-simpleajaxuploader": "*"

**Comment by far-rainbow** [comment]
# composer require --prefer-dist skeeks/yii2-widget-simpleajaxloader "*"
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package skeeks/yii2-widget-simpleajaxloader could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by skeeks-semenov** [comment]
`skeeks/yii2-widget-simpleajaxuploader`

corrected typos in readme
